name: auth
description: Auth Service
publish_to: none
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  conduit: ^3.2.9
  jaguar_jwt: ^3.0.0
  mime: ^1.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

assets:
  - public/avatars/
